export const ROUTES = {
  Home: '/',
  About: '/about',
  Search: '/search',
  SermonDetail: (slug: string) => `/sermons/${slug}`,
  Books: '/books',
  MorningAndEvening: '/books/morning-and-evening',
  FaithsCheckBook: '/books/faiths-check-book',
  TreasuryOfDavid: '/books/treasury-of-david',
  BookReader: (book: string) => `/books/${book}`,
  SwordAndTrowel: '/sword-and-trowel',
  MagazineArticle: (slug: string) => `/sword-and-trowel/${slug}`,
  Blog: '/blog',
  BlogPost: (slug: string) => `/blog/${slug}`,
  Articles: '/articles',
  Article: (slug: string) => `/articles/${slug}`,
  ConferenceMediaItem: (slug: string) => `/conference-media/${slug}`,
  Library: '/library',
  DigitalTour: '/library/digital-tour',
} as const;
