const { withFaust } = require('@faustwp/core');

let legacySermonRedirects = [];
try {
  legacySermonRedirects = require('./legacy-redirects.js');
} catch (_) {
  // file is generated by `wp spurgeon export-redirects` after content migration
}

/**
 * Legacy capital-case URL redirects from the old Base44 routes.
 * Disabled in development on macOS because the OS-level case-insensitive
 * filesystem causes Next.js to match `/about` against `/About` and loop.
 * Production (Linux on WP Engine Atlas) is case-sensitive and works fine.
 */
const ENABLE_LEGACY_REDIRECTS = process.env.NODE_ENV === 'production';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'media.base44.com' },
      { protocol: 'https', hostname: '*.wpengine.com' },
      { protocol: 'https', hostname: 'spurgeon.org' },
      { protocol: 'https', hostname: 'spurgeon.wpengine.com' },
    ],
  },
  async redirects() {
    const legacyPageRedirects = ENABLE_LEGACY_REDIRECTS ? [
      { source: '/Home',              destination: '/',                          permanent: true },
      { source: '/About',             destination: '/about',                     permanent: true },
      { source: '/Books',             destination: '/books',                     permanent: true },
      { source: '/Search',            destination: '/search',                    permanent: true },
      { source: '/MorningAndEvening', destination: '/books/morning-and-evening', permanent: true },
      { source: '/FaithsCheckBook',   destination: '/books/faiths-check-book',   permanent: true },
      { source: '/TreasuryOfDavid',   destination: '/books/treasury-of-david',   permanent: true },
      { source: '/SwordAndTrowel',    destination: '/sword-and-trowel',          permanent: true },
      { source: '/Library',           destination: '/library',                   permanent: true },
      { source: '/DigitalTour',       destination: '/library/digital-tour',      permanent: true },
      {
        source: '/BookReader',
        has: [{ type: 'query', key: 'book', value: '(?<book>.*)' }],
        destination: '/books/:book',
        permanent: true,
      },
    ] : [];

    return [
      ...legacyPageRedirects,
      // Always redirect old sermon detail UUID-based URLs through the API lookup
      {
        source: '/SermonDetail',
        has: [{ type: 'query', key: 'id' }],
        destination: '/api/legacy-redirect?id=:id',
        permanent: false,
      },
      ...legacySermonRedirects,
    ];
  },
};

module.exports = withFaust(nextConfig);
