const { withFaust } = require('@faustwp/core');

let legacySermonRedirects = [];
try {
  legacySermonRedirects = require('./legacy-redirects.js');
} catch (_) {
  // file is generated by `wp spurgeon export-redirects` after content migration
}

// Bulk redirects from the spurgeon.org WordPress install onto the new
// headless URL shapes. Generated from the legacy sitemap + WP-CLI dumps
// (see docs/redirect-mapping-report.md). Kept in a separate file so the
// WP-migration map can be regenerated independently of legacy-redirects.js.
let wpLegacyRedirects = [];
try {
  wpLegacyRedirects = require('./wp-legacy-redirects.js');
} catch (_) {
  // file is generated by scripts/build-wp-legacy-redirects.mjs
}

// Legacy Base44 capital-case redirects are permanently disabled. The Atlas
// Envoy proxy applies Next.js redirect rules case-insensitively, so
// { source: '/About', destination: '/about' } matches lowercase /about and
// creates a self-referential 308 loop for every page in the list.
const ENABLE_LEGACY_REDIRECTS = false;

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'media.base44.com' },
      { protocol: 'https', hostname: '*.wpengine.com' },
      { protocol: 'https', hostname: 'spurgeon.org' },
      { protocol: 'https', hostname: 'spurgeon.wpengine.com' },
    ],
  },
  async redirects() {
    const legacyPageRedirects = ENABLE_LEGACY_REDIRECTS ? [
      { source: '/Home',              destination: '/',                          permanent: true },
      { source: '/About',             destination: '/about',                     permanent: true },
      { source: '/Books',             destination: '/books',                     permanent: true },
      { source: '/Search',            destination: '/search',                    permanent: true },
      { source: '/MorningAndEvening', destination: '/books/morning-and-evening', permanent: true },
      { source: '/FaithsCheckBook',   destination: '/books/faiths-check-book',   permanent: true },
      { source: '/TreasuryOfDavid',   destination: '/books/treasury-of-david',   permanent: true },
      { source: '/SwordAndTrowel',    destination: '/sword-and-trowel',          permanent: true },
      { source: '/Library',           destination: '/library',                   permanent: true },
      { source: '/DigitalTour',       destination: '/library/digital-tour',      permanent: true },
      {
        source: '/BookReader',
        has: [{ type: 'query', key: 'book', value: '(?<book>.*)' }],
        destination: '/books/:book',
        permanent: true,
      },
    ] : [];

    return [
      ...legacyPageRedirects,
      // Always redirect old sermon detail UUID-based URLs through the API lookup
      {
        source: '/SermonDetail',
        has: [{ type: 'query', key: 'id' }],
        destination: '/api/legacy-redirect?id=:id',
        permanent: false,
      },
      ...legacySermonRedirects,
      ...wpLegacyRedirects,
    ];
  },
};

// Faust auto-injects a redirect that matches any URL with `?preview=true`
// and sends it to /preview by default. This site uses bespoke per-CPT pages
// instead of Faust's catch-all template renderer, so route Faust's preview
// trigger through our own /api/preview handler — which validates the shared
// secret, sets the Next.js preview cookie, and redirects to the correct
// per-CPT page (e.g. /blog/<slug>, /sermons/<slug>).
module.exports = withFaust(nextConfig, { previewDestination: '/api/preview' });

import('@opennextjs/cloudflare').then(m => m.initOpenNextCloudflareForDev());
